name: Style and type checks

on: [push, pull_request]

jobs:
  Style-Type-Check:
    name: Style and Type Checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      id: install-dep
      run: |
        python -m pip install pip
        python -m pip install --upgrade pip
    - name: Black checks
      if: always() && steps.install-dep.outcome == 'success'
      run: |
        pip install black
        make black VFLAG=-v
    - name: Flake8 checks
      if: always() && steps.install-dep.outcome == 'success'
      run: |
        pip install flake8
        make flake8 VFLAG=-v
    - name: Mypy checks
      if: always() && steps.install-dep.outcome == 'success'
      run: |
        pip install mypy
        make mypy VFLAG=-v
